### ISSUE TITLE
大神，Dell 9020mt可以支持nvme SSD吗？EFI里面是否可以从别的EFI拷贝nvme驱动来支持？

### ISSUE THREAD

**Issue by learningendless** [mingcheng/dell-optiplex-9020m-hackintosh#11]
大神，Dell 9020mt可以支持nvme SSD吗？EFI里面是否可以从别的EFI拷贝nvme驱动来支持？我看目前efi的driver里面是没有nvme的efi驱动，是不是可以从别的efi里拷贝一个过来来支持nvme？想要买个nvme的ssd，通过pcie转nvme板卡来插一个M.2接口的nvme协议的SSD来提升性能，不知道是否可行？（总的来说，不升级bios，在机械硬盘里分出一个efi分区，bios引导这个efi，这个efi里如果有nvme的efi驱动的话，可以从nvme SSD启动macos）

**Comment by heibaihui** [comment]
你好可以交流下吗 我同款机型显卡驱动不了。

**Comment by learningendless** [comment]
> 你好可以交流下吗 我同款机型显卡驱动不了。

集成显卡不需要特殊的操作吧？

**Comment by heibaihui** [comment]
> > 你好可以交流下吗 我同款机型显卡驱动不了。
> 
> 集成显卡不需要特殊的操作吧？

安装完显存只有7m ！想用这里的efi文件驱动显存就卡住进不去桌面。。郁闷

**Comment by scofieldpeng** [comment]
这个只支持sata协议的，不支持nvme

**Comment by mingcheng** [comment]
Q87 芯片组不支持 NVME
