### ISSUE TITLE
cpu温度80度 轻度使用正常吗

### ISSUE THREAD

**Issue by heibaihui** [mingcheng/dell-optiplex-9020m-hackintosh#13]
![IMG_20190621_210507](https://user-images.githubusercontent.com/4918372/59925150-069e6980-946a-11e9-9f29-bb225917447d.jpg)

**Comment by hanxi2719** [comment]
魔改U是不是液金的？好像温度会低点

**Comment by Dimision** [comment]
同魔改4870HQ，待机温度60+，散热感人。。压力测试五分钟，机箱烫的手都不敢摸
