### ISSUE TITLE
老哥，请问下，这个EFI  HD4600可以直接使用吗？cpu i5 4670t，感谢

### ISSUE THREAD

**Issue by hanxi2719** [mingcheng/dell-optiplex-9020m-hackintosh#15]

**Comment by sgx800** [comment]
看起来是不行，作者使用的CPU不具有代表性。我的CPU是i7-4785T，核显HD4600引导失败，出现停止符号，用楼下的淘宝EFI成功安装10.14.6。

**Comment by mingcheng** [comment]
HD4600 可以使用的，但是需要重新驱动显卡，可以参考这里 https://www.tonymacx86.com/threads/install-intel-hd-4600-to-mac-sierra-hackintosh.210119/

**Comment by cbourne142857** [comment]
I realise this is old but in case it helps somebody - I can say it worked for me with i5 4690T / HD4600.

Method I used:
1) Use gibMacOS to download Mojave image and create clover USB drive
2) Delete EFI directory and replace with one from this github
3) Install OSX
4) I had some kernel panics, so replaced  kexts with latest versions, then it worked great.
