### ISSUE TITLE
4980hq可使用吗

### ISSUE THREAD

**Issue by wdrich** [mingcheng/dell-optiplex-9020m-hackintosh#17]
你好 请问同样5200的显卡的4980hq可以使用吗？这机器的散热可以压的住4870hq吗？

**Comment by li3p** [comment]
刚组装了一台是可以用的，但是应该 DELL 有功率墙，温度还只是70度左右的时候，用 CineBench 压力 CPU，CPU 就一直工作在2.8G的主频了，上不去。所以HQ 系列的47W 的 U 用在这机器上有些可惜了。

**Comment by mingcheng** [comment]
可以使用，但是考虑到功率还有散热的问题，建议还是用低一点的CPU

**Comment by wdrich** [comment]
谢谢大家的建议
