### ISSUE TITLE
升级到10.15系统 其他都正常  就是那个新出的随航功能 不能用 

### ISSUE THREAD

**Issue by heibaihui** [mingcheng/dell-optiplex-9020m-hackintosh#19]
网上说机型太老了，大神有试过没有

**Comment by shm007g** [comment]
请问你用的什么U，看issue有的人说它们没法用这个EFI直接升级呢？

**Comment by mingcheng** [comment]
因为是生产机的关系，目前还没时间升级到10.15

**Comment by flipphos** [comment]
> 网上说机型太老了，大神有试过没有

3代，4代的cpu的黑果都不支持随航的，我都试过。7代cpu的就可以。8代更不用说。

你的休眠唤醒正常吗？升级到10.15.2了没有？

**Comment by mingcheng** [comment]
> > 网上说机型太老了，大神有试过没有
> 
> 3代，4代的cpu的黑果都不支持随航的，我都试过。7代cpu的就可以。8代更不用说。
> 
> 你的休眠唤醒正常吗？升级到10.15.2了没有？

这台机子目前我还停留再 10.14.6 ，暂时不打算升级

**Comment by mingcheng** [comment]
已经升级到 10.15，测试了下发现的确是 CPU 的问题，暂时不打算折腾了。
