### ISSUE TITLE
dell 7050 （塔式机箱）能否完美黑？

### ISSUE THREAD

**Issue by awkj** [mingcheng/dell-optiplex-9020m-hackintosh#2]
Dell 官网链接 https://www.dell.com/zh-cn/work/shop/%E5%95%86%E7%94%A8%E5%8F%B0%E5%BC%8F%E6%9C%BA-%E4%B8%80%E4%BD%93%E6%9C%BA%E5%8F%8A%E5%8F%B0%E5%BC%8F%E5%B7%A5%E4%BD%9C%E7%AB%99/optiplex-7050%E5%BE%AE%E5%A1%94%E5%BC%8F%E6%9C%BA%E5%92%8C%E5%B0%8F%E5%9E%8B%E6%9C%BA/spd/optiplex-7050-desktop

**Comment by wooramel** [comment]
理论上说应该可以
