### ISSUE TITLE
关于网卡转接的选择

### ISSUE THREAD

**Issue by kingcos** [mingcheng/dell-optiplex-9020m-hackintosh#3]
非常感谢共享这么详细的配置以及资源！

~~您说的「硬件方面从淘宝购买了准系统以及 4870HQ 的 CPU、两根 8g 的 DDR3 1600 三星内存条、固态硬盘为来自京东的三星 860 EVO 、蓝牙和无线网卡使用 MacBook Air 拆机的 BCM943224，搭配了 ngff 转接卡，同时 SATA 硬盘位安装了拆机的 500g 日立机械硬盘用作时间胶囊。」ngff 转接卡应该是把 BCM943224 转接为 9020m 的网卡接口对吧？然后 SSD 可以放在 m2 走 SATA 协议，机械可以直接走原有的 SATA 接口。~~

上面的问题已经查到了，准备购买 Intel 545s m2 接口 SATA 协议的 SSD。但是网卡转接还是不是特别清楚，BCM943224 准备选择 [https://m.tb.cn/h.3vg3ULL?sm=8f7a55](https://m.tb.cn/h.3vg3ULL?sm=8f7a55)，不过他是蓝牙 3.0 的，另外的一个店显示是 4.0，不知道是不是哪个标错了，转接卡不知是否是这样的：[https://m.tb.cn/h.3vgey26?sm=9518fc](https://m.tb.cn/h.3vgey26?sm=9518fc)。

另外想问一下，按照这个镜像是否可以装呢 [【黑果小兵】macOS Mojave 10.14.3 18D42 正式版 with Clover 4859原版镜像](https://blog.daliansky.net/macOS-Mojave-10.14.3-18D42-official-version-with-Clover-4859-original-image.html)？

黑苹果新手，多谢啦。

**Comment by kingcos** [comment]
已经查好了，准备下单搞一搞～

**Comment by xuhaoyang** [comment]
@kingcos 
https://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-9563937738.16.44a22fd2W5uLMn&id=572987831185
https://item.taobao.com/item.htm?spm=a1z0d.6639537.1997196601.136.de757484CU3Q15&id=561741574447

延长+转接+ BCM94360CS2 
考虑下

**Comment by kingcos** [comment]
@xuhaoyang 

好的，感谢啦，我再查查看。

**Comment by xuhaoyang** [comment]
@kingcos 帮别人装了一个，m2 ngff A/E 转苹果16针的 转接卡 + BCM94360CS2，刚好塞得下，需要拿热熔胶一类的固定一下

**Comment by kingcos** [comment]
@xuhaoyang 好的，再次感谢！
