### ISSUE TITLE
跑FCPX导出时 CPU屏幕降至800mhz

### ISSUE THREAD

**Issue by xuhaoyang** [mingcheng/dell-optiplex-9020m-hackintosh#5]
最近临时用这台机导出一些fcpx的东西，发现导出母带时，CPU频率会快速跌到800mhz，实际上温度不到75，请问下， @mingcheng ，有遇到类似问题吗

![屏幕快照 2019-05-03 上午3.17.36.png](https://i.loli.net/2019/05/10/5cd54ee44abec.png)

**Comment by mingcheng** [comment]
貌似没有碰到类似的问题，DSDT 这块打过补丁了吗？

**Comment by wklxd** [comment]
为啥关了这个issue，降频的问题解决了吗？
