### ISSUE TITLE
VGA

### ISSUE THREAD

**Issue by M0CRT** [mingcheng/dell-optiplex-9020m-hackintosh#9]
你好

干得好，谢谢。

你能帮助我吗？

VGA端口为你工作？除了VGA之外，我都在工作。

谢谢

**Comment by Dimision** [comment]
I can only connect it to my monitor with DP cable so far, and it works flawlessly.
If i connect them with VGA cable ,the machine even can't boot up.

**Comment by mingcheng** [comment]
VGA does not supported for ANY Hackintosh
